<a href="https://colab.research.google.com/github/hieukien/Ph-n-t-ch-c-m-x-c-b-ng-NLP/blob/main/%C4%91%E1%BB%93_%C3%A1n_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow_datasets as tfds
imdb,info=tfds.load("imdb_reviews",with_info=True,as_supervised=True)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete84VXKD/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete84VXKD/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete84VXKD/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
import numpy as np
train_data,test_data=imdb["train"],imdb["test"]

In [ ]:
train_sentences=[]
test_sentences=[]
train_lable=[]
test_lable=[]
for s,l in train_data:
  train_sentences.append(str(s.numpy()))
  train_lable.append(str(l.numpy))
for s,l in test_data:
  test_sentences.append(str(s.numpy()))
  test_lable.append(str(l.numpy))

In [ ]:
train_lable=np.array(train_lable)
test_lable=np.array(test_lable)

In [ ]:
import re
corpus = []
for review in train_sentences :
  review = re.sub("[^a-zA-Z]"," ", review)
  review=review.lower()
  review=word_tokenize(review)
  ps = PorterStemmer()
  review = [ps.stem(word) for word in review if word not in stopwords.words("english")]
  review =" ".join(review)
  corpus.append(review)


KeyboardInterrupt: ignored

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
print( vectorizer.fit_transform(corpus).todense() )



[[1 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 1]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0]]


In [ ]:
X

<4x26 sparse matrix of type '<class 'numpy.int64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test =train_test_split(X, train_lable, train_size = 0.8, random_state = 0)

In [ ]:
X_train

<20000x1500 sparse matrix of type '<class 'numpy.int64'>'
	with 1368562 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, Y_train)

TypeError: ignored